name: thesis-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - jupyterlab
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pip
  - pip:
      - "minari[hf]"
      - d3rlpy
      - gymnasium
      - mujoco
      - mujoco-py
      - robosuite
      - pettingzoo
      - torch
      - wandb
      - moviepy
      - pybullet
      - pygame